---
title: "Seminar 2 - Formative Task for your first summative."
format: pdf
editor: visual
---

## Formative Exercise for Summative 1.

Download the following file from Moodle. 'kc_house_data.csv'. This dataset contains house sale prices for King County, which includes Seattle. It includes homes sold between May 2014 and May 2015. We are a company that wants to improve a pricing model for house prices in this area. In order to do this we want to know what are the most important predictors for housing prices. In pairs. Do the following. 

1. Create an R markdown document.

2. Use R to create some descriptive statistics.

3. Use R to plot some descriptive statistics.

4. Use R to plot pairs of variables and identify any relationships. 

5. Identify some correlations

6. Create some single linear regression models, identify the best of these.

7. Create some multiple linear regression models, identify the best of these.

8. Write down some conclusions.

9. Export your markdown document as a pdf.